#!/bin/bash
#PBS -l vmem=24GB
#PBS -l walltime=36:00:00
#PBS -N muts_tfbs
#PBS -M zian.liu@bcm.edu
#PBS -o /mount/samee/zianl_overflow/motif_seqcon/
#PBS -e /mount/samee/zianl_overflow/motif_seqcon/

cd $PBS_O_WORKDIR
ls

# Add mutratepkg to PATH
export PATH=/mount/samee/zianl_overflow/VCF_processing_update/bin/:$PATH

# Add modules
module load bedtools/2.29.2
module load bedops/2.4.2

mutratepkg count-kmermuts \
  -i "/mount/samee/zianl_overflow/data_1kgphase3/frqs/1kgsamples_allchr.frq" \
  -c "/mount/samee/zianl_overflow/motif_seqcon/motifbeds/*.bed" \
  -G "/mount/samee/Genomes/hg19_ucsc/hg19.fa" \
  -m "0.05" \
  -k 7 \
  -o "mutcounts/"
